### ISSUE TITLE
Command support

### ISSUE THREAD

**Issue by emarsman** [openxc/openxc-ios-framework#1]
framework currently only supports "device_id" and "version" commands. Need to add the remaining from https://github.com/openxc/openxc-message-format/blob/master/JSON.mkd#commands. Some of these may come along with protobuf support.

**Comment by vkanishk** [comment]
Added the below commands:
1. version
2. device id
3. passthrough
4. acceptance bypass
5. payload format
in pull request - https://github.com/openxc/openxc-ios-app-demo/pull/22

Still need to add more commands:
1. platform details
2. RTC configuration, etc. 
Will be doing it next

**Comment by vkanishk** [comment]
opening separate issues for platform details & RTC Config command
