### ISSUE TITLE
Network data source support for openxc-ios-framework

### ISSUE THREAD

**Issue by SuperChloe** [openxc/openxc-ios-framework#12]
Currently, the [Android OpenXC framework](https://github.com/openxc/openxc-android) supports input from a network data source. This allows users to test the framework with the [OpenXC vehicle simulator](https://github.com/openxc/openxc-vehicle-simulator). Are there any plans to add network data source support to the iOS framework?

**Comment by emarsman** [comment]
Hi Chloe,

Yes, it is in the plans. But it will not happen until 2017 based on other higher priority tasks. If you and Lloyd (https://groups.google.com/forum/#!topic/openxc/7LMRM-jYSp8) wanted to take a stab at it on a branch, we would appreciate the help!

Regards,
Eric

**Comment by RanjaniOS** [comment]
Hi Chloe,
This is done in Openxc framework in branch "next".You can check it now.If you find any issue you could report here .

Regards
Ranjan kumar sahu
