### ISSUE TITLE
Support payload in diagnostic requests

### ISSUE THREAD

**Issue by vkanishk** [openxc/openxc-ios-framework#22]
Payload is an optional argument and is not supported in the framework for diagnostic requests. Add support for payload in framework

- branch - payloadInDiag

**Comment by vkanishk** [comment]
with payload as NSString/NSInteger/Data the request is not processed at all. So no response is received. VI is not responding to a command with a payload from iOSBeing an optional parameter, a response must be received. 
Same request when sent from python gives correct response. 

The issue can be with the format being sent from iOS framework or the way its processed by the VI/firmware in BLE. 

Needs more debugging

**Comment by WuhanMonkey** [comment]
We also tested and made sure that the framework was sending correct 20B chunk frame from BLE with/without payload. This bug persist across emulator, Sync development kit and the vehicle (Mustang, Continental). 

In master branch the payload is not integrated into the JSON we sent out at all. Now it is included in this branch.

**Comment by vkanishk** [comment]
This is fixed and merged to master now. Issue was that the payload was being sent as NSString but without quotes. This was making it a non string when sent in request. Have changed the code to send payload as "string" and now it works. 

https://github.com/openxc/openxc-ios-framework/pull/25
