### ISSUE TITLE
Determine default signal setup (firmware) for BLE connection in JSON and Protobuf

### ISSUE THREAD

**Issue by emarsman** [openxc/openxc-ios-framework#7]
Since BLE cannot support all data, determine rates for standard OpenXC signals that will allow robust data connections in both JSON and Protobuf formats. These will end up being recommendations and a compiled release for BLE firmware builds.

**Comment by PPRAKA30** [comment]
Closing as a note was made on the data sets page on the website.
Reference: openxc/openxcplatform.com#110
