### ISSUE TITLE
Add support for iOS10, XCode8 & swift3

### ISSUE THREAD

**Issue by vkanishk** [openxc/openxc-ios-framework#8]

**Comment by dgorev** [comment]
Hello.
May I ask about estimated completion date of this issue? I need it to estimate completion date of our project that is written on swift3 and can't use swift2-implementation of openxc.

Thanks!

**Comment by vkanishk** [comment]
@dgorev  The code for swift3 is modified and is under branch "swift3migration". I am in process of testing it. Feel free to take the code and use, it if you want to. Any help will be appreciated :)

**Comment by vkanishk** [comment]
Migration to Swift3 is complete and code is merged. 
Release v1.1.0 https://github.com/openxc/openxc-ios-framework/releases/tag/v1.1.0
